---
- name: Verificar y corregir políticas de seguridad en routers Cisco
  hosts: cisco_routers
  tasks:
    - name: Verificar configuración de contraseña segura
      ios_command:
        commands:
          - "show running-config | include username admin"
      register: result
      changed_when: false
      failed_when: "'username admin' not in result.stdout_lines"
      ignore_errors: yes

    - name: Corregir contraseña de administrador
      ios_config:
        lines:
          - "username admin privilege 15 secret NuevaContrasena"  # Reemplaza "NuevaContrasena" con tu nueva contraseña segura
      when: "'username admin' not in result.stdout_lines"

    # Puedes agregar más tareas para corregir otras políticas de seguridad aquí

