---
- name: Configurar interfaz Loopback
  hosts: cisco_routers
  gather_facts: no
  tasks:
    - name: Incluir variables por dispositivo
      include_vars:
        file: variables.yml

    - name: Configurar interfaz Loopback
      ios_config:
        lines:
          - interface Loopback0
          - description Interfaz Loopback
          - ip address {{ dispositivos[inventory_hostname]['loopback_ip'] }} 255.255.255.255
      register: result

    - name: Guardar la configuración
      ios_command:
        commands:
          - write memory
      when: result.changed

    - name: Verificar la configuración
      ios_command:
        commands:
          - show ip interface brief | include Loopback0
      register: verification

    - name: Imprimir resultado de la verificación
      debug:
        var: verification.stdout_lines
